### PR TITLE
Added file needed for support under Spigot 1.21

### PR DESCRIPTION
**Pull request by UnicodeSnowmanDev**
Added experimental support for 1.21 Spigot.
Unfortunately, due to the lack of a Folia 1.21 build, some concessions had to be made.
Building will fail if the server version is updated to 1.21 in the pom, as folia-api has no viable builds. To solve this, I've left the server version as 1.20.1, and confirm that it both builds **and** runs under Spigot/PaperMC 1.21
While not preferred, this does allow for operators of 1.21 servers to use the plugin in these months while we wait on Folia 1.21 support.

### CODE REVIEW

**Comment by Lauriichan** [comment]
I don't understand why this is necessary?
I tried SmoothTimber on 1.21 and it worked fine without any changes.
See #91

**Comment by UnicodeSnowmanDev** [comment]
You are 100% correct, I just tested it again on a clean install of the latest paper with no issues. It looks like I may have had some odd conflicts with an early experimental build that caused it to unload itself after printing the version warning.
Closing this now.

**Comment by Lauriichan** [comment]
If u check out https://github.com/SourceWriters/SmoothTimber/blob/legacy/src/main/java/com/syntaxphoenix/spigot/smoothtimber/version/changer/v1_16xChanger.java#L23 u will see that multiple newer versions are also covered by some implementations for older versions

**Comment by Lauriichan** [comment]
Okay, thank you for your contribution anyway!
U may have had an older build, the version restriction/detection system was reworked quite „recently“ so it is probably quite likely.

**Pull request closed without merging**
